site_name: Documentation

nav:
  - Introduction: introduction.md
  - Getting Started: getting-started.md
  - Basic Usage: usage.md
  - Limitations: limitations.md
  - Changelog: changelog.md
  - Resources: resources.md
  - Home: https://findmyclient.org


theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
  font:
    text: Inter
    code: JetBrains Mono

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
    