site_name: FindMyClient
site_url: https://docs.findmyclient.org/

nav:
  - Home: index.md
  - Getting Started: 
      - Introduction: introduction.md
      - API Token: api-token.md
      - Search Endpoint: search-endpoint.md
      - Search Parameters: parameters.md
      - Result Endpoint: result-endpoint.md
      - Enrichment Endpoint: enrichment-endpoint.md
      - Basic Usage: usage.md
      - Limitations: limitations.md
  - Integration:
      - n8n: n8n.md
  - Releases:
      - v0.0.8: v0-0-8.md
      - v0.0.7: v0-0-7.md
      - v0.0.6: v0-0-6.md
      - v0.0.5: v0-0-5.md
      - v0.0.2: v0-0-2.md
      - v0.0.1: v0-0-1.md
  - Resources:
      - FindMyClient.org: about.md
      - Privacy Policy: privacy-policy.md
      - Terms & Conditions: terms-conditions.md
  - Pricing:
      - Pricing Table: pricing-table.md
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/favicon.png
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: default
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - content.code.select
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github 

repo_url: https://github.com/Rottie420/findmyclient.git
repo_name: Rottie420/findmyclient

copyright: Copyright &copy; 2026 FindMyClient.org

plugins:
  - search
  - tags:
      tags_file: tags.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
    - stylesheets/extra.css

extra_javascript:
  - js/home-class.js
